#!/bin/sh
DEST=~/.minecraft/mods

rm -r $DEST
mkdir $DEST

set -e

# chococraft is not yet updated
# CoFH core is not yet updated
# KBI's tinker construct recovery not yet updated

cp appeng-rv13-b-mc162.jar       $DEST

#cp Basic_Components_v1.0.0.3.jar $DEST
cp BILLUND1.0.zip                $DEST
cp buildcraft-A-4.0.2.jar        $DEST
cp binnie-mods-1.8-dev2.jar      $DEST
cp "BiblioCraft[v1.4.1].zip"     $DEST
cp BiblioWoods\[Forestry\]\[v1.2\].zip        $DEST
cp BiblioWoods\[ExtraBiomesXL\]\[v1.0\].zip   $DEST
cp BiblioWoods\[Natura\]\[v1.0\].zip   $DEST

# not yet updated # cp binnie-mods-1.7.2.jar         $DEST
#cp Chococraft_2.8.9.zip $DEST
cp 'CodeChickenCore 0.9.0.5.jar' $DEST
# cp 'CoFHCore-1.5.2.5.jar' $DEST
cp 'ComputerCraft1.56.zip'       $DEST
cp 'ChickenChunks 1.3.3.2.jar'   $DEST
cp 'Copious-Dogs-Mod-1.6.2.jar'  $DEST

# cp 'Dalek Mod 1.6.2 - forge.zip' $DEST
cp denLib-1.6.2-3.1.23.jar       $DEST
cp 'DartCraft Beta 0.2.05.jar'    $DEST
cp 'Dynmap-1.9-alpha-3-forge-9.10.0.jar'     $DEST
#cp 'DragonAPI-MC16 v3.zip'                   $DEST

cp 'EnderStorage 1.4.3.3.jar'    $DEST
cp ExtrabiomesXL-universal-1.6.2-3.14.1.jar $DEST
cp EmasherResource-1.2.1.2.zip   $DEST
cp EngineersToolbox-1.1.3.0.zip  $DEST

cp forestry-A-2.3.0.1.jar        $DEST
cp Familiars_API_1.6.2c.zip              $DEST
cp Familiars_DefaultMobPack_1.6.2a.zip   $DEST
cp Familiars_ExtendedFamPack_1.6.2a.zip  $DEST
cp Familiars_HerobrineFamPack_1.6.2a.zip $DEST

# magic bees not yet updated
#cp mapwriter-2.0.9.zip           $DEST
cp Minimapsync1.6.2_b0.3.1.jar     $DEST
cp \[1.6.2\]ReiMinimap_v3.4_01.zip $DEST
# Needs Mekanism
#cp MekanismGenerators-v5.5.7.175.jar $DEST
#cp Mekanism-v5.5.7.175.jar       $DEST
cp mystcraft-uni-1.6.2-0.10.6.00.zip $DEST
#cp 'MFR-50.zip'                  $DEST

cp Natura_1.6.2_2.1.9.jar        $DEST
cp neiaddons-1.6.2-1.9.0.r40.jar $DEST
cp NEIPlugins-1.1.0.0pre1.jar    $DEST
cp 'NotEnoughItems 1.6.1.4.jar'  $DEST

cp OpenPeripheral-0.2.1-preview8.jar      $DEST


# cp 'PluginsforForestry-1.6.2-3.1.18.jar'  $DEST
# cp 'PowerCrystalsCore-21.jar'             $DEST

# cp 'RotaryCraft-MC16 v3.zip'              $DEST

cp 'StevesCarts2.0.0.a132.zip'            $DEST

cp 'TConstruct_1.6.2_1.4.5.1.jar'           $DEST
# Thaumcraft not yet updated
# thaumic tinkerer not yet updated
# thermal expansion not yet updated
cp 'Translocator 1.1.0.12.jar'    $DEST
cp 'twilightforest-1.19.3.jar'   $DEST

# cp 'UniversalElectricity_Core_v2.1.0.158.jar' $DEST

cp VillageInfo_Forge_1.6.2_2.0-b3.zip    $DEST

# Millenaire wants to be a special snowflake
# cp 'Millenaire5.1.9.zip' $DEST

unzip Millenaire5.1.9.zip
cp -r 'Millenaire 5.1.9/Put in mods folder/'* $DEST
rm -r 'Millenaire 5.1.9'



# File does not normally end with a newline
echo "" >> $DEST/millenaire-custom/config-custom.txt
echo "quest_list_key=B" >> $DEST/millenaire-custom/config-custom.txt

# Dalek mod sounds are resources, not a mod
unzip -o -d $DEST/../assets/sound/ 'Dalek Mod Resources - 1.6.2.zip' -x ReadMe.txt



CONFIG=$DEST/../config
#rm -r $CONFIG || true
#mkdir $CONFIG

cp -r config/* $CONFIG

(
 rm -r server-build
 mkdir server-build
 cd server-build
 rsync -r ../forge-server/ .
 rsync -r $DEST .
 rsync -r $DEST ../config .
 rm mods/*ReiMinimap*
 rm mods/*NEIPlugins*
 chmod +x minecraftforge-*
)



#./new-launcher-test/minecraft-1.6.2-launcher.jar


