#!/bin/sh
DEST=~/.minecraft/mods

rm -r $DEST
mkdir $DEST

set -e

cp live-mods/*.jar $DEST
cp live-mods/*.zip $DEST

# Millinaire wants to be a special snowflake
# cp 'Millenaire5.1.9.zip' $DEST

unzip Millenaire5.1.10.zip
cp -r 'Millenaire 5.1.10/Put in mods folder/'* $DEST
rm -r 'Millenaire 5.1.10'

# File does not normally end with a newline
echo "" >> $DEST/millenaire-custom/config-custom.txt
echo "quest_list_key=B" >> $DEST/millenaire-custom/config-custom.txt

CONFIG=$DEST/../config
#rm -r $CONFIG || true
#mkdir $CONFIG

cp -r config/* $CONFIG

(
 rm -r server-build
 mkdir server-build

 rsync -r forge-server/ server-build/

 mkdir server-build/mods/
 cp live-mods/*.jar server-build/mods/
 cp live-mods/*.zip server-build/mods/

 unzip Millenaire5.1.10.zip
 cp -r 'Millenaire 5.1.10/Put in mods folder/'* server-build/mods/
 rm -r 'Millenaire 5.1.10'

 mkdir server-build/config
 cp -r config/* server-build/config/

 # Most client-side mods don't mind being on the server too.  These few, though, do mind.
 rm server-build/mods/*ReiMinimap*
 rm server-build/mods/*NEIPlugins*
 rm server-build/mods/*WikiLink*

 chmod +x server-build/minecraftforge-*
)



#./new-launcher-test/minecraft-1.6.2-launcher.jar


